# Check auto merge contiditons of PR and proceed merging
name: "check auto merge contiditons and proceed merging"

# Event on a comment (in PR)
on:
  issue_comment:
    types: [created]
jobs:
  # Check auto merge contiditons of PR and proceed merging
  automerge:
    # Apply this job if it is a PR and by OWNER with '/approve' comment
    # TODO: the section contains('seokho-son jihoon-seo hermitkim1') needs to be updated or automated
    if: ${{ github.event.issue.pull_request && (contains('seokho-son jihoon-seo hermitkim1', github.event.comment.user.login) || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/approve') }}
    # This job runs on Ubuntu-latest (Ubuntu 20.04 LTS checked on 2022-09-06)
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
      # Check author_association is OWNER
      - name: Check author_association
        run: |
          echo event.comment.user.login is ${{ github.event.comment.user.login }}
          echo event.comment.author_association is ${{ github.event.comment.author_association }}
          echo Hello, this workflow is allowed to specific OWNERS.
      
      # Apply 'approved' label when OWNER left '/approve' comment
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            approved
      
      # AutoMerging if this PR has MERGE_LABELS: approved, lgtm (not wip, hold)
      - name: automerge-lgtm-approved
        uses: "pascalgn/automerge-action@v0"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "approved,lgtm,!wip,!hold"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: "automerge"
          UPDATE_METHOD: "merge"
