# Action by command-style comments (inspired by Kubernetes Prow)
name: "action by command-style comments"

# Event on a comment (in issue and PR)
on:
  issue_comment:
    types: [ created, edited ]
  pull_request_review_comment:
    types: [ created, edited ]

jobs:
  execute:
    # Execute when author_association of the comment is OWNER or MEMBER
    if: ${{ github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER' }}
    # This job runs on Ubuntu-latest (Ubuntu 20.04 LTS checked on 2022-09-06)
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    # Execute action according to commands
    steps:
      # Check author_association
      - name: Check author_association
        run: |
          echo event.comment.user.login is ${{ github.event.comment.user.login }}
          echo event.comment.author_association is ${{ github.event.comment.author_association }}
          echo Hello, this workflow is allowed to OWNER and MEMBER.     

      # Action according to command (by jpmcb/prow-github-actions)  
      - name: Action according to command
        if: ${{ startsWith(github.event.comment.body, '/') }}
        uses: jpmcb/prow-github-actions@v1.1.3
        with:
          prow-commands: '/assign 
            /unassign
            /approve 
            /retitle 
            /area 
            /kind 
            /priority 
            /remove 
            /lgtm 
            /close 
            /reopen 
            /lock 
            /milestone 
            /hold 
            /cc 
            /uncc'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
